//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOCheckoutTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IOCheckoutTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM201.
        /// </summary>
        internal static string _201 {
            get {
                return ResourceManager.GetString("201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM202.
        /// </summary>
        internal static string _202 {
            get {
                return ResourceManager.GetString("202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM203.
        /// </summary>
        internal static string _203 {
            get {
                return ResourceManager.GetString("203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM204.
        /// </summary>
        internal static string _204 {
            get {
                return ResourceManager.GetString("204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM207.
        /// </summary>
        internal static string _207 {
            get {
                return ResourceManager.GetString("207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM214.
        /// </summary>
        internal static string _214 {
            get {
                return ResourceManager.GetString("214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM215.
        /// </summary>
        internal static string _215 {
            get {
                return ResourceManager.GetString("215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM216.
        /// </summary>
        internal static string _216 {
            get {
                return ResourceManager.GetString("216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM217.
        /// </summary>
        internal static string _217 {
            get {
                return ResourceManager.GetString("217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM217R.
        /// </summary>
        internal static string _217R {
            get {
                return ResourceManager.GetString("217R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM218.
        /// </summary>
        internal static string _218 {
            get {
                return ResourceManager.GetString("218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM237.
        /// </summary>
        internal static string _237 {
            get {
                return ResourceManager.GetString("237", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM238.
        /// </summary>
        internal static string _238 {
            get {
                return ResourceManager.GetString("238", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM239.
        /// </summary>
        internal static string _239 {
            get {
                return ResourceManager.GetString("239", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM240.
        /// </summary>
        internal static string _240 {
            get {
                return ResourceManager.GetString("240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM240R.
        /// </summary>
        internal static string _240R {
            get {
                return ResourceManager.GetString("240R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM241.
        /// </summary>
        internal static string _241 {
            get {
                return ResourceManager.GetString("241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM242.
        /// </summary>
        internal static string _242 {
            get {
                return ResourceManager.GetString("242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM247.
        /// </summary>
        internal static string _247 {
            get {
                return ResourceManager.GetString("247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FBM248.
        /// </summary>
        internal static string _248 {
            get {
                return ResourceManager.GetString("248", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $AOUT.
        /// </summary>
        internal static string AOUT {
            get {
                return ResourceManager.GetString("AOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $BIN.
        /// </summary>
        internal static string BIN {
            get {
                return ResourceManager.GetString("BIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $BOUT.
        /// </summary>
        internal static string BOUT {
            get {
                return ResourceManager.GetString("BOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $CIN.
        /// </summary>
        internal static string CIN {
            get {
                return ResourceManager.GetString("CIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $CINR.
        /// </summary>
        internal static string CINR {
            get {
                return ResourceManager.GetString("CINR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $COUT.
        /// </summary>
        internal static string COUT {
            get {
                return ResourceManager.GetString("COUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $COUTR.
        /// </summary>
        internal static string COUTR {
            get {
                return ResourceManager.GetString("COUTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cole.labhart@se.com.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty string in email form.
        /// </summary>
        internal static string Email_Form {
            get {
                return ResourceManager.GetString("Email Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email has been sent.
        /// </summary>
        internal static string Email_Sent {
            get {
                return ResourceManager.GetString("Email Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the form..
        /// </summary>
        internal static string EmptyForm {
            get {
                return ResourceManager.GetString("EmptyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Checkout Feature Request.
        /// </summary>
        internal static string Feature_Request_Subject {
            get {
                return ResourceManager.GetString("Feature Request Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Instructions_for_Using_IO_Checkout_Tool {
            get {
                object obj = ResourceManager.GetObject("Instructions_for_Using_IO_Checkout_Tool", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $MAIN.
        /// </summary>
        internal static string MAIN {
            get {
                return ResourceManager.GetString("MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $MCIN.
        /// </summary>
        internal static string MCIN {
            get {
                return ResourceManager.GetString("MCIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $MCOUT.
        /// </summary>
        internal static string MCOUT {
            get {
                return ResourceManager.GetString("MCOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Checkout Bug Report.
        /// </summary>
        internal static string Report_Bug_Subject {
            get {
                return ResourceManager.GetString("Report Bug Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $RIN.
        /// </summary>
        internal static string RIN {
            get {
                return ResourceManager.GetString("RIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $RINR.
        /// </summary>
        internal static string RINR {
            get {
                return ResourceManager.GetString("RINR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ROUT.
        /// </summary>
        internal static string ROUT {
            get {
                return ResourceManager.GetString("ROUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ROUTR.
        /// </summary>
        internal static string ROUTR {
            get {
                return ResourceManager.GetString("ROUTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send the current version of the IO Checkout Tool. My current version is.
        /// </summary>
        internal static string Version_Request_Body {
            get {
                return ResourceManager.GetString("Version Request Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Checkout Latest Version.
        /// </summary>
        internal static string Version_Request_Subject {
            get {
                return ResourceManager.GetString("Version Request Subject", resourceCulture);
            }
        }
    }
}
